openapi: 3.0.0
info:
  description: >-
    "TCL4 requires the submission of vehicle-centric data including from
    specialized sensors mounted on the vehicle which may collect data at various
    sampling rates.  These models are referenced in the Data Management Plan
    (DMP)."
  version: "1.0.0-oas3"
  title: API endpoints for UTM TCL DMP CON vehicles data collection
  termsOfService: 'http://uam.arc.nasa.gov/terms'
  contact:
    name: 'NASA Ames Research Center, Aviation Systems Division'
    url: 'https://utm.arc.nasa.gov/'
    email: joseph.rios@nasa.gov
  license:
    name: NASA Open Source Agreement
    url: 'https://ti.arc.nasa.gov/opensource/nosa/'
paths:
  /con-wx-operating-point-data-station:
    post:
      summary: Upload array of ConWxOperatingPointDataStation models.
      responses:
        '200':
          description: Data received. No content returned.
          content:
            '*/*':
              schema:
                #$ref: https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/develop/datacollection/openapi/v3/schema/schma-uam-dmp-common-3.0.yaml#/components/schemas/UAMRestResponse
        '400':
          description: Bad request. Typically validation error. Fix your request and retry.
          content:
            '*/*':
              schema:
                #$ref: https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/develop/datacollection/openapi/v3/schema/schma-uam-dmp-common-3.0.yaml#/components/schemas/UTMRestResponse
        '401':
          description: Invalid or missing access_token provided.
          content:
            '*/*':
              schema:
                #$ref: https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/develop/datacollection/openapi/v3/schema/schma-uam-dmp-common-3.0.yaml#/components/schemas/UTMRestResponse
        '403':
          description: >-
            Forbidden. Do not retry with same access token. Reason not provided,
            but do you have the right scopes? Does uss_name match the sub claim?
          content:
            '*/*':
              schema:
                #$ref: https://raw.githubusercontent.com/nasa/utm-apis/v4-draft/utm-domains/utm-domain-commons.yaml#/definitions/UTMRestResponse
                $ref: https://raw.githubusercontent.com/nasa/uam-apis/develop/datacollection/openapi/v3/schema/schma-uam-dmp-common-3.0.yaml#/components/schemas/UTMRestResponse
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: >-
                  https://raw.githubusercontent.com/nasa/uam-apis/develop/datacollection/openapi/v2/schema/schema-uam-wx-data-station-2.0.yaml#/definitions/ConWxOperatingPointDataStation
        description: Array of ConWxOperatingPointDataStation models
        required: true
servers:
  - url: 'https://utmregistry.arc.nasa.gov./api/v4'