openapi: 3.0.0
servers:
  - description: Fleet Operator-PSU
    url: 'https://arc.nasa.gov/npsu/operator'
info:
  description: |- 
    Interface between Fleet Operator (FO) to Provider of Services for Urban Air Mobility (PSU) to get availability of resources for planning operations from Resource Planning Service (RPS). 
    - Provider of Services for Urban Air Mobility (PSU) API, see https://github.com/nasa/uam-apis/blob/master/openapi/psu/psu_api.yml
    - Discovery & Synchronization Service (DSS) API, see https://github.com/nasa/uam-apis/blob/master/openapi/psu/dss_api.yml
    - Capacity Information Service (CIS) model in https://github.com/nasa/uam-apis/blob/master/openapi/cis/cis_model.yml
  version: 3.1.3
  title: AMP TCL-1 Fleet Operator-PSU API
  contact:
    name: NASA

# Assumption: Resource Planning Service has already input 
# available capacities, constraints, etc. for each resource.
# Based on Sequence Diagrams documented in https://atmconfluence.arc.nasa.gov/display/ATMX/X5+Sequence+Diagrams+and+APIs
security:
  - Authority:
    - operations.non-sensitive.read
    - operations.non-sensitive.write

tags:
  - name: Adaptation
    description: >-
      Endpoints exposed between Operator-PSU for interactions about airspace structure or adaptation data.
  - name: Resources
    description: >-
      Endpoints exposed between Operator-PSU for interactions about capacities of resources.
  - name: Scheduling
    description: |-
      Endpoints exposed by Resources Planning Services (RPS) for resource scheduling based on spacing and sequencing constraints.
  - name: Operations
    description: Add and view Operation. From X4 UAM Operator API with changes for X5.
  - name: Messages
    description: Add and view Operator Messages. From X4 UAM Operator API.
  - name: Positions
    description: Add Operation Positions. From X4 UAM Operator API.
  - name: Constraints for elevated privileges
    description: Add and view Constraints.  Constraints endpoints require elevated FIMS privileges. From X4 UAM Operator API.
    
paths:
  /resources_availability/query:
    post:
      tags:
        - Resources
      security:
        - Authority:
            - operations.non-sensitive.read
      summary: >-
        Get availability of resources for scheduling an operation. Availability is mainly determined based on time when an aircraft will arrive, a.k.a. Estimated Time of Arrival (ETA), at resources.
      description: |- 
        Factors like aircraft speed, altitude, etc. may be needed to determine resource availability. Return earliest available time when all resources, part of 4-D trajectory of operational intent, are available. 
  /resources_available_volumes/query:
    post:
      tags:
        - Resources
      security:
        - Authority:
            - operations.non-sensitive.read
      summary: >-
        Get volumes for resources, with availability checks, needed by an operation intent for submission to a PSU network. 
      description: |-
        Includes availability confirmation for all resources managed by RPS-DCB. Availability is mainly determined based on time when an aircraft will arrive, a.k.a. Estimated Time of Arrival (ETA), at resources. Factors like aircraft speed, altitude, etc. may be needed to determine resource availability. 4-D volumes, a.k.a. extents, for each resource is needed for operational intent submission to a PSU network.
  /resources_volumes/query:
    post:
      tags:
        - Resources
      security:
        - Authority:
            - operations.non-sensitive.read
      summary: >-
        Get all 4-D resource volumes, with start and end timings, for each 4-D trajectory point planned at resource within an operation without availability checks.
      description: |- 
        Return array of 4-D, with start and end timings, resource volumes without checking for resource availability against 4-D trajectory point planned at resource.
  /resources_scheduling:
    post:
      tags:
        - Scheduling
      security:
        - Authority:
            - operations.non-sensitive.read
      summary: >-
        Request service to check timings in 4-D trajectory against each given resource constraint information, like spacing, overtake rules, etc. between aircraft at resources. If needed, adjust Estimated Time of Arrival (ETA) at trajectory points within given 4-D trajectory so aircraft arriving at entry, exit, crossing or merge resource, within controlled airspace, do not violate constraints. 
      description: |-
        Factors like aircraft speed, altitude, etc. may be needed to determine availability of resources. Minimum delay of arrival time at a resource needs to satisfy spacing criteria for that resource. Spacing should be an actual usable slot, not just a delay required to follow aircraft to make room; thus, should consider leading and trailing spacings between aircraft in front and aircraft behind. Return 4-D trajectory, with or without adjusted timings, and one of these scheduling outcomes:
        
            - FEASIBLE_AS_IS means timings in operation's 4-D trajectory were not changed.
            - FEASIBLE_WITH_CHANGE means timings in operation's 4-D trajectory were changed.
            - INFEASIBLE means unable to adjust operation's 4-D trajectory even by changing timings would still not satisfy resource constraints.
  /adaptation/{adaptationname}:
    get:
      tags:
      - Adaptation
      security:
        - Authority:
          - operations.non-sensitive.read
      summary: Retrieve the specified adaptation details
  #
  # From existing X5 UAM Operator API schema components
  #      
  "/messages":
    post:
      tags:
        - Messages
      summary: Submit Message for a GUFI
      security:
        - Authority:
          - operations.non-sensitive.write
  "/messages/{gufi}":
    get:
      tags:
        - Messages
      summary: Get Messages by GUFI
      security:
        - Authority:
          - operations.non-sensitive.read
  "/operations":
    post:
      tags:
        - Operations
      summary: Propose a new Operation or Submit 'Proposed' operation to get 'Accepted'
      security:
        - Authority:
          - operations.non-sensitive.write
      description: >-
        If the requestBody doesn't contain a GUFI, a random GUFI shall be assigned to the
        Operation.
        If the requestBody contains a GUFI, then the supplied GUFI will be
        used for the new operation.
    put:
      tags:
        - Operations
      summary: Update an Operation
      security:
        - Authority:
          - operations.non-sensitive.write
      description: >-
        Update an existing operation, which is specified by gufi in the request
  "/operations/{gufi}":
    get:
      tags:
        - Operations
      summary: Retrieve an Operation by GUFI.
      description: Retrieve an Operation by GUFI.  Returns a 404 if GUFI is not found.
      security:
        - Authority:
          - operations.non-sensitive.read
  "/positions":
    post:
      tags:
        - Positions
      summary: Submit a Position to NUP
      description: >-
        Submit a Position to NUP.
      security:
        - Authority:
          - operations.non-sensitive.write
      operationId: postPosition
components:
  securitySchemes:
    #
    # From existing X5 UAM Operator API schema components
    #      
    Authority:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://some.host/fimsAuthServer/oauth/token
          scopes:
            operations.non-sensitive.read: Allow read of non-sensitive operations
            operations.non-sensitive.write: Allow write of non-sensitive operations
      description: |-
        Authorization from, or on behalf of, an authorization authority.  This authority shall issue access tokens that are JSON Web Tokens as defined in RFC 7519, using the `RS256` algorithm for the signature, publish to all providers the public key for verifying that signature, and implement standard OAuth server discovery mechanisms as described in RFC 8414.
        The following fields shall be included in the JWT claim for access tokens issued by this authority:
            * `iss`, with the URL at which the token generation request was received.
            * `exp`, with a time no further than 1 hour in the future.
            * `sub`, with unique ID of the client requesting the access token.
            * `scope`, with an array of strings indicating the scopes granted.
            * `jti`, according to RFC 7519.
        Clients shall provide these access tokens in an `Authorization` header in the form `Bearer <token>` in accordance with RFC 6750.
          