---
openapi: 3.0.1
info:
  title: Constraint Identification Service (CIS) Model Definition
  version: 2.0.1
  description: Data model definitions for constraint information that would have been provided 
     by the proposed Constraint Information Service (CIS) if it were implemented. 
     <br><br>
     *Note - In X5, this CIS service is not implemented as a service, but rather, the data is provided as a static JSON file to all test participants. The JSON data file follows this data model definition.*
paths:
  /example:
    get:
      summary: Example of a get call to CIS for airspace constraint information.
        This example has been added as a placeholder for future functionality
        implementation for a CIS service.  This request will not be implemented
        as defined here.
      responses:
        '200':
          description: Return the constraints information within the airspace.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdaptationConstraint"

components:          
  schemas:
    AdaptationConstraint:
      description: |-
        The constraint information for applicable waypoints within an identified Adaptation ID.
      required:
        - id
        - name
        - version
        - adaptation_hash
        - waypoints
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUIDv4'
        name:
          description: Associated name for this adaptation that matches the name for the adaptation defined in ASDS
          type: string
          example: DFW
        version:
          description: Version of the applicable ASDS data
          type: string
          example: 0.0.2-UAMX4
        adaptation_hash:
          $ref: '#/components/schemas/AdaptationHash'
        configuration:
          description: Associated airspace configuration for this adaptation that matches the airspace configuration 
            for the adaptation defined in ASDS 
          type: string
          nullable: true
          example: North
          enum:
              - North
              - NorthEast
              - East
              - SouthEast
              - South
              - SouthWest
              - West
              - NorthWest
        waypoints:
          type: array
          items:
            $ref: '#/components/schemas/WaypointConstraint'
          minItems: 1

    WaypointConstraint:
      description: |-
        One or many constraints for a defined adaptation waypoint. 
        - Identifier is associated with waypoint identifier from adaptation.
      required:
        - id
        - name
        - constraints
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUIDv4'
        name:
          type: string
          description: Associated name that matches the name for the waypoint defined in ASDS
          example: DF100
        constraints: 
          type: array
          items:
            $ref: '#/components/schemas/Constraint'
          minItems: 1
    
    Constraint:
      description: >-
        Constraint information for a waypoint.
      required:
        - constraint_id
        - constraint_type
        - constraint_properties
      type: object
      properties:
        constraint_id:
          $ref: '#/components/schemas/UUIDv4'
        constraint_type:
          type: string
          description: |-
            Types of constraint at waypoint are:
            - FLOW_RATE_CONSTANT
              Constant time rate of separation.
            - FLOW_RATE_FIXED_BIN
              Constraint values for number of operations within a fixed time bin with duration in seconds. 
              - Fixed time bin should start at top-of-the-hour and evenly divide up an hour. For more details, see description for unit = seconds in ConstraintValue.
            - FLOW_RATE_ROLLING_BIN
              Constraint values for number of operations within a rolling time bin starting at end of previous time bin. Duration of time bin is in seconds. 
              - Rolling time bin does not necessarily start at top-of-the-hour.
            - SEPARATION_DISTANCE
              Constraint value, in meters, for separation distance between aircraft.
            - SEPARATION_TEMPORAL
              Constraint value, in seconds, for temporal separation between aircraft.
            - SEQUENCE
              Constraint ensure the sequence within a segment is maintain where the sequence at the entry fix (ConstraintProperty->property_type->DEPENDENCY_POINT) is equal to the that of the exit fix (WaypointConstraint->name). 
          enum:
            - FLOW_RATE_CONSTANT
            - FLOW_RATE_FIXED_BIN
            - FLOW_RATE_ROLLING_BIN
            - SEPARATION_DISTANCE
            - SEPARATION_TEMPORAL  
            - SEQUENCE
        constraint_properties:
          type: array
          items:
            $ref: '#/components/schemas/ConstraintProperty'
          minItems: 1
      
    ConstraintProperty:
      description: Constraint property value which define the constraint parameters. Each property is uniquely defined and contain required metadata for adequate description.
      type: object
      required:
       - property_id
       - property_type
       - property_value
       - property_unit
      properties:
        property_id:
          $ref: '#/components/schemas/UUIDv4'
        property_type:
          type: string
          description: |- 
            Type of constraint the numeric value is associated with.
            - OPERATIONS
              - Number of operations within time bin for <i>FLOW_RATE_FIXED_BIN</i> or <i>FLOW_RATE_ROLLING_BIN</i>
            - DURATION
              - Time, defined in seconds, during which constraint continues.
            - DISTANCE
              - Amount of space, defined in meters, between aircraft
            - DEPENDENCY_POINT
              Known adaptation point name. This point is a dependency to the constraint associated WaypointConstraint.
          enum:
            - OPERATIONS
            - DURATION
            - DISTANCE
            - DEPENDENCY_POINT
        property_value:
          description: The property value for constraint at this WaypointConstraint.  The type of this value is based on the property_unit and should be casted appropriately given the unit definitions.
          type: string
        property_unit:
          type: string
          description: |-
            - NUMERIC
                Represents any numerical number. (e.g. Total number of a collection of items like operations, aircraft, etc.)
            - SECONDS
                Number of seconds.
                - for duration for a constraint time bin or interval value. Time intervals or bins are half-open with the lower bound included and upper bound excluded. For example, time bin can be interpreted as [12:00, 12:12) where 12:00 is inclusive lower bound.
                - <i>FLOW_RATE_FIXED_BIN</i> duration should evenly divide up an hour, for example, 5 seconds will provide 12 time bins.
            - M
                Meters of separation between aircraft
                  - Same as altitude unit enum, see https://raw.githubusercontent.com/nasa/uam-apis/x4/openapi/psu/dss_api.yml#/components/schemas/Altitude
            - STRING
                Property that is of type string.
          enum:
            - NUMERIC
            - SECONDS
            - M
            - STRING
            
    UUIDv4:
      description: |-
        Universally-unique identifier (version 4).
        UUID for adaptation or constraint waypoint should match UUIDs defined in ASDS.
      maxLength: 36
      minLength: 36
      type: string
      format: uuid
      pattern: >-
        '^[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-4[0-9a-fA-F]{3}\\-[89abAB][0-9a-fA-F]{3}\\-[0-9a-fA-F]{12}$'
      example: d290f1ee-6c54-4b01-90e6-d701748f0851

    AdaptationHash:
      description: |-
        SHA256 hash of the Adaptation ID data from ASDS
      required:
        - hash
      type: object
      properties:
        hash:
          type: string
          maxLength: 64
          minLength: 64
      example: 6c5dce661d01e69cabe71753501090b1b95af97d59bf4b593124e3963c139c8a
