---
openapi: 3.0.1
info:
  title: Resources Registry (RR) Model Definition
  version: 3.0.0
  description: Data model definitions for Resources Registry that could be provided 
     by a Resources Registry Service if it were implemented. 
     <br><br>
     *Note - In X5, data is provided as a static JSON file to all test participants.  
           The JSON data file follows this data model definition.*
paths:
  /example:
    get:
      summary: Example of a get call to RR Service for managed resources information within the airspace.
        This example has been added as a placeholder for future functionality
        implementation for a RR service.  This request will not be implemented
        as defined here.
      responses:
        '200':
          description: Return the managed resources information within the airspace.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourcesRegistry"

components:          
  schemas:
    ResourcesRegistry:
      description: |-
        The capacity information for applicable waypoints within an identified Adaptation ID.
      required:
        - id
        - name
        - version
        - adaptation_hash
        - resources_details
      type: object
      properties:
        id:
          description: Associated UUID for this adaptation that matches the UUID for the adaptation defined in ASDS
          anyOf:
          - $ref: '#/components/schemas/UUIDv4'
        name:
          description: Associated name for this adaptation that matches the name for the adaptation defined in ASDS
          type: string
          example: DFW
        version:
          description: Version of the applicable ASDS data
          type: string
          example: 0.0.2-UAMX5
        adaptation_hash:
          $ref: '#/components/schemas/AdaptationHash'
        resources_details:
          type: array
          items:
            $ref: '#/components/schemas/ResourceDetails'

    ResourceDetails:
      description: |-
        Information about a resource available:
        - URL of service managing resource
      type: object
      required:
        - name
        - id
        - base_url
      properties:
        name:
          type: string
          description: >-
            Name of resource matches ASDS data and 'point_designator' field in the TrajectoryPoint4D object within the operational intent - see https://raw.githubusercontent.com/nasa/uam-apis/x4/openapi/psu/psu_api.yml#/components/schemas/TrajectoryPoint4D.
          example: DF101
        id:
          description: >-
            Associated UUID for this point that matches the UUID for the waypoint defined in ASDS
          anyOf:
            - $ref: '#/components/schemas/UUIDv4'
        base_url:
          $ref: '#/components/schemas/BaseURL'
      
    UUIDv4:
      description: |-
        Universally-unique identifier (version 4).
      maxLength: 36
      minLength: 36
      type: string
      format: uuid
      pattern: >-
        '^[0-9a-fA-F]{8}\\-[0-9a-fA-F]{4}\\-4[0-9a-fA-F]{3}\\-[89abAB][0-9a-fA-F]{3}\\-[0-9a-fA-F]{12}$'
      example: d290f1ee-6c54-4b01-90e6-d701748f0851
      
    BaseURL:
      description: |-
        The base URL of a resource managing service implementation of part or all of the PSU-RPS API. Per the PSU-RPS API, the full URL
        of a particular resource managing service can be constructed by appending, e.g., `/rps/v1/resources_availability/query/{resource}` to this base URL.
        Accordingly, this URL may not have a trailing '/' character.
      type: string
      example: https://uam.rps1.nasa.gov

    AdaptationHash:
      description: |-
        SHA256 hash of the Adaptation ID data from ASDS
      required:
        - hash
      type: object
      properties:
        hash:
          type: string
          maxLength: 64
          minLength: 64
          example: 6c5dce661d01e69cabe71753501090b1b95af97d59bf4b593124e3963c139c8a

