openapi: 3.0.0
info:
  version: "v1.0-oas3"
  title: vehicle surveillance metadata
  description: OpenAPI 3.0 compliant definitions for vehicle metadata for ADS-B
      Out data.

components:
  schemas:
      adsb_vehicle_metadata:
        type: object
        required:
          - icao_address
          - time_start
        properties:
          icaoAddress:
            type: string
            pattern: '^[0-9a-fA-F]{6}$'
            description: 24 bit hexadecimal ICAO address of the aircraft
          squawk:
            type: string
            maxLength: 4
            minLength: 4
            pattern: "^[0-7][0-7][0-7][0-7]$"
            description: Squawk code. octal
          callsign:
            type: string
            maxLength: 8
            pattern: "^[A-Za-z0-9]+$"
            description: call sign of the aircraft
          additionalNotes:
            type: string
            maxLength: 1000
          time_start:
            type: string
            format: date-time
          time_end:
            type: string
            format: date-time
          adsbDeviceIdentifier:
            type: string
            maxLength: 64
            description: pingStation calls their unique ID a GUID, but it is
                only 32 bits. Other device or source identifiers are possible.
