openapi: 3.0.0
info:
  version: "v1.0-oas3"
  title: ADS-B Out
  description: OpenAPI 3.0 compliant definitions for ADS-B Out data.

components:
  schemas:
      ADSBObject:
        type: object
        required:
          - aircraft
        properties:
          aircraft:
            type: array
            items:
              $ref: 
                '#/components/schemas/ADSBModel'

      ADSBModel:
        type: object
        required:
          - icaoAddress
        properties:
          icaoAddress:
            type: string
            pattern: '^[0-9a-fA-F]{6}$'
            description: ICAO of the aircraft
          trafficSource:
            type: integer
            enum: [0,1]
            description: 1090 MHz or 978 MHz
              0 = 1090
              1 = UAT
          latDD:
            type: number
            description: Latitude expressed as decimal degrees
          lonDD:
            type: number
            description: Longitude expressed as decimal degrees
          altitudeMM:
            type: number
            description: Geometric altitude or barometric pressure altitudein millimeters
          headingDE2:
            type: number
            description: Course over ground in centi-degrees
          horVelocityCMS:
            type: integer
            description: Horizontal velocity in centimeters/sec
          verVelocityCMS:
            type: integer
            description: Vertical velocity in centimeters/sec with positive being up
          squawk:
            type: number
            pattern: '^[0-7]{4}$'
            description: Squawk code
          altitudeType:
            type: integer
            enum: [0,1]
            description: Altitude Source
              0 is pressure
              1 is geometric
          callsign:
            type: string
            pattern: '^[A-Z0-9]+ *$'
          emitterType:
            type: integer
            enum: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39]
            description: >-
              Category type of the emitter 
              0  = No aircraft type information
              1  = Light (ICAO) < 15,500 lbs
              2  = Small -15,500 to 75,000 lbs
              3  = Large -75,000 to 300,000 lbs
              4  = High Vortex Large (e.g., B757)
              5  = Heavy (ICAO) -> 300,000 lbs
              6  = Highly Maneuverable > 5G acceleration and high speed
              7  = Rotorcraft
              8  = (Unassigned)
              9  = Glider/sailplane
              10 = Lighter than air
              11 = Parachutist/sky diver
              12 = Ultralight/hang glider/paraglider
              13 = (Unassigned)
              14 = Unmanned aerial vehicle
              15 = Space/trans-atmospheric vehicle
              16 = (Unassigned)
              17 = Surface vehicle-emergency vehicle
              18 = Surface vehicle-service vehicle
              19 = Point Obstacle (includes tethered balloons)
              20 = Cluster Obstacle
              21 = Line Obstacle
              22-39 = (Reserved)
          utcSync:
            type: number
            description: UTC time flag
          timeStamp:
            $ref: 
              '#/components/schemas/ADSBtimestamp'
          detail:
            $ref:
              '#/components/schemas/Detail'

      Detail:
        type: object
        properties:
          navIntegrity:
            type: integer
            enum: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
            description: Navigation integrity category (NIC)
              0  =RC >=37.04 km (20 NM) Unknown Integrity
              1  = RC < 37.04 km (20 NM) RNP-10 containment radius
              2  = RC < 14.816 km (8 NM) RNP-4 containment radius
              3  = RC < 7.408 km (4 NM) RNP-2 containment radius
              4  =RC < 3.704 km (2 NM) RNP-1 containment radius
              5  = RC < 1852 m (1 NM) RNP-0.5 containment radius
              6  = RC < 1111.2 m (0.6 NM) RNP-0.3 containment radius
              7  = RC < 370.4 m (0.2 NM) RNP-0.1 containment radius
              8  = RC < 185.2 m (0.1 NM) RNP-0.05 containment radius
              9  = RC < 75 m and VPL < 112 m e.g., SBAS, HPL, VPL
              10 = RC < 25 m and VPL < 37.5 m e.g., SBAS, HPL, VPL
              11 = RC < 7.5 m and VPL < 11 m e.g., GBAS, HPL, VPL
              12-15 = (Reserved)
          navAccuracy:
            type: integer
            enum: [0,1,2,3,4,5,6,7]
            description: Navigation accuracy category(NACv)
              0 = Unknown or >= 10 m/s Unknown >= 50 feet (15.24 m) per second 
              1 = < 10 m/s    < 50 feet (15.24 m) per second                  
              2 = < 3 m/s     < 15 feet (4.57 m) per second          
              3 = < 1 m/s     < 5 feet (1.52 m) per second                    
              4 = < 0.3 m/s < 1.5 feet (0.46 m) per second                    
              5-7 = (Reserved) (Reserved)                                       
          verVelocitySrc:
            type: integer
            enum: [0,1]
            description: Vertical velocity source
              0 = Pressure
              1 = Geometric
          emergencyStatus:
            type: integer
            enum: [0,1,2,3,4,5,6]
            description: Emergency status
              0 = No-Emergency
              1 = General Emergency
              2 = Lifeguard/Medical
              3 = Min Fuel
              4 = No Comm
              5 = Unlawful Interference
              6 = Downed Aircraft
          sysIntegrityLevel:
            type: integer
            enum: [0,1,2,3]
            description: SourceIntegrity Level(SIL)
              indicates the probability of the reported horizontal position exceeding the containment radius defined by the NIC
              (from AC 20-165)
              3 ≤1x10-7 Per Hour or Sample
              2 ≤1x10-5 Per Hour or Sample
              1 ≤ 1x10-3 Per Hour or Sample
              0 > 1x10-3 Per Hour or Sample  or Unknown
          sysDesignAssurance:
            type: integer
            enum: [0,1,2,3]
            description: SystemDesign Assurance(SDA)
              indicated the probability of an ADS-B system malfunction causing false or misleading position
              (from AC 20-165)
              1 Probability of exceeding NIC containment radius is based on per sample
              0 Probability of exceeding NIC containment radius is based on per hour
          airGroundState:
            type: integer
            enum: [0,1,3]
            description: Airborne or ground
              0 = Airborne subsonic condition
              1 = Airborne supersonic condition
              3 = On ground condition
          svHeadingType:
            type: integer
            enum: [0,1,2,3]
            description: Track angle from heading  
              0 = Data Not Available
              1 = True Track Angle
              2 = Magnetic Heading
              3 = True Heading
          verticalVelType:
            type: integer
            enum: [0,1]
            description: Vertical rate information
              0 = Pressure
              1 = Geometric
          navPositionAccuracy:
            type: integer
            enum: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
            description: The reported State Vector has sufficient position accuracy for the intended use(NACp)
              0  = EPU >= 18.52 km (10 NM)
              1  =EPU < 18.52 km (10 NM)
              2  = EPU < 7.408 km (4 NM)
              3  = EPU < 3.704 km (2 NM)
              4  = EPU < 1852 m (1NM)
              5  = EPU < 926 m (0.5 NM)
              6  = EPU < 555.6 m (0.3 NM)
              7  = EPU < 185.2 m (0.1 NM)
              8  = EPU < 92.6 m (0.05 NM)
              9  =EPU < 30 m and VEPU < 45
              10 = EPU < 10 m and VEPU < 15
              11 = EPU < 3 m and VEPU < 4 m
              12-15 = (Reserved)
          navVelocityAccuracy:
            type: integer
            enum: [0,1,2,3,4,5,6,7]
            description: The least accurate velocity component being transmitted (NACv)
              0 = Unknown or >= 10 m/s Unknown or >= 50 feet (15.24 m) per second
              1 = < 10 m/s < 50 feet (15.24 m) per second
              2 = < 3 m/s < 15 feet (4.57 m) per second
              3 = < 1 m/s < 5 feet (1.52 m) per second
              4 = < 0.3 m/s < 1.5 feet (0.46 m) per second
              5-7 = (Reserved)
          navIntegrityBaro:
            type: integer
            enum: [0,1]
            description: Barometer checked (NICbaro)
              0 = Barometric Pressure Altitude has NOT been cross checked
              1 = Barometric Pressure Altitude has been cross checked
          geoVerticalAccuracy:
            type: integer
            enum: [0,1,2]
            description: Geometric Vertical Accuracy(GVA)
              0 Unknown or > 150 meters
              1 ≤ 150 meters
              2 ≤ 45 meter
          tcasAcasOperating:
            type: integer
            enum: [0,1]
            description: Aircraft is fitted with a TCAS (ACAS) computer and that computer is turned on and operating in a mode that can generate Resolution Advisory (RA) alerts
          tcasAcasAdvisory:
            type: integer
            enum: [0,1]
            description: TCAS II or ACAS computer is currently issuing a Resolution Advisory
              todo, check actual values.
          identSwActive:
            type: integer
            enum: [0,1]
            description: ident switch is activated
              todo, check actual values.
          atcServicesRecvd:
            type: integer
            enum: [0,1]
            description: ATC pilot message mode setting
              0 = Not receiving ATC messages
              1 = Receiving ATC message
          magHeading:
            type: integer
            enum: [0,1]
            description: True north or magnetic north
              0 = True north
              1 = Magnetic north
          utcCoupledCondition:
            type: integer
            enum: [0,1]
            description: Represents if the Ground Station is UTC-Coupled 
              0 = Ground Station is not UTC coupled
              1 = Ground Station is UTC coupled

  #    ADSB1090ES:
  #      type: object
  #      properties:
          surveilStatus:
            type: integer
            enum: [0,1,2,3]
            description: Surveillance status
              0 = No Condition
              1 = permanent alert
              2 = temp alert
              3 = SPI
          baroaltDiffMM:
            type: integer
            description: Difference between the pressure altitude and the gnss altitude in mm
# not a java valid name. Can't ingest it right now. 2/24/2020
#          1090esMopsVersion:
#            type: integer
#            enum: [1,2]
#            description: 1 = DO-260A, 2 = DO-260B           
  #    ADSBUAT:
  #      type: object
  #      properties:
          secondaryAltType:
            type: integer
            enum: [0,1]
            description: Altitude source
              0 = Pressure
              1 = Geometric
          secondaryAltitudeMM:
            type: integer
            description: Geometric altitude or barometric pressure altitude in millimeters
          tisBSiteId:
            type: integer
            description: The tisBSiteId is unit-less and is from the a transmitted TISb UAT message signifies which uplink tower transmitted the TISb frame
          transmitMSO:
            type: integer
            enum: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63]
            description: the transmitMSO is the 6bit field from the transmitted UAT message which should signify which MSO the message was transmitted in.  MSO's can range from 0 to 3951 but only transmit the 6 LSB's of the actual MSO if transmitted.
          addressQualifier:
            type: integer
            enum: [0,1,2,3,4,5,6,7]
            description: Defines the type of target that delivered the data
              0 = ADS-B target with ICAO 24-bit
              1 = Reserved for National use
              2 = TIS-B target with ICAO 24-bit address
              3 = TIS-B target with track file identifier
              4 = Surface Vehicle
              5 = Fixed ADS-B Beacon
              6-7 = (Reserved)
          uatMopsVersion:
            type: integer
            enum: [0,1]
            description: 1 = DO-282A, 2 = DO-282B
          callSignID:
            type: integer
            enum: [0,1]
            description: 0 = Fightplan, 1 = CallSign

  #    RID:
  #      type: object
  #      properties:
          uvin:
            type: string
            format: uuid
          toLatDD:
            type: number
            description: Takeoff latitude expressed as decimal degrees
          toLonDD:
            type: number
            description: Takeoff longitudeexpressed as decimal degrees
          missionType:
            type: integer
            enum: [0,1,2,3,4,5,6,7,8,9,10,11]
            description: Numeric representation of the type of mission being flown
              0 = recreational
              1 = photography/videography
              2 = media
              3  = point/structure inspection
              4 = agriculture
              5 = mapping
              6 = surveillance
              7 = law enforcement / first responder
              8 = search and rescue
              9 = delivery
              10= urgent delivery
              11 =other
          phoneNumber:
            type: integer
            description: Phone number attached to the mission.
              todo sic. Cannot possibly be right. long or string?
          fltplanFiled:
            type: integer
            enum: [0,1]
            description: NOTAM/UOA flight plan filed flag
              todo, not checked, no example

# timestamp stolen from .. todo: should use commons
      ADSBtimestamp:
        type: string
        format: date-time
        minLength: 22
        maxLength: 24
        example: '2015-08-20T14:11:56.118Z'
