openapi: 3.0.0
info:
  description: |-
    X3 Data Models
  version: "1.0.0"
  title: X3 Data Models

paths:
  /waypoint:
      post:
        summary: Upload a single instance of the waypoint model
        responses:
            '200':
              $ref: '#/components/responses/r200'
            '204':
              $ref: '#/components/responses/r204'
            '400':
              $ref: '#/components/responses/r400'
            '401':
              $ref: '#/components/responses/r400'
            '403':
              $ref: '#/components/responses/r403'
            '409':
              $ref: '#/components/responses/r409'
            '429':
              $ref: '#/components/responses/r429'
        requestBody:
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Waypoint'
          description: Upload array of Waypoint models
          required: true

  /psu-exchange:
    post:
      summary: Upload an object of models
      responses:
        '200':
          $ref: '#/components/responses/r200'
        '204':
          $ref: '#/components/responses/r204'
        '400':
          $ref: '#/components/responses/r400'
        '401':
          $ref: '#/components/responses/r400'
        '403':
          $ref: '#/components/responses/r403'
        '409':
          $ref: '#/components/responses/r409'
        '429':
          $ref: '#/components/responses/r429'

      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/PSUExchange'
        description: Upload an object of models, containing array of uss exchange
        required: true

components:
  schemas:
    Timestamp:
      description: >-
        Timestamps MUST follow the guidance set forth in RFC3339.
        Note that this format specifies UTC time indicated by a trailing 'Z'.
        Note that this format specifies date and time separation with a 'T'.
      type: string
      format: date-time
      minLength: 24
      maxLength: 24
      pattern: "^([0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\\.[0-9]{3})Z$"
      example: '2015-08-20T14:11:56.118Z'

    LatLonAlt:
      type: object
      required:
        - Latitude
        - Longitude
        - Altitude
      description: >-
        Object used to define a location. Latitude and Longitude should have precision of 7 or more digits. WGS84 altitude. (ft)
      properties:
        Latitude:
          description: >-
            Degrees of latitude north of the equator, with reference to the WGS84 ellipsoid. Should have precision of 7 or more digits.
          type: number
          format: double
        Longitude:
          description: >-
            Degrees of longitude east of the Prime Meridian, with reference to the WGS84 ellipsoid. Should have precision of 7 or more digits.
          type: number
          format: double
        Altitude:
          description: >-
            The numeric value of the WGS84 altitude.
          type: number
          format: double

    UTMRestResponse:
      type: object
      required:
        - http_status_code
        - message
      properties:
        http_status_code:
          type: integer
          minimum: 100
          exclusiveMinimum: false
          maximum: 599
          exclusiveMaximum: false
        message:
          type: string
          maxLength: 500
      example:
        http_status_code: 400
        message: Bad Request. Invalid JSON?

    PSUExchange:
        required:
          - "exchanged_data_pk"
          - "exchanged_data_type"
          - "source_psu"
          - "target_psu"
          - "time_request_initiation"
          - "time_request_completed"
          - "actual_http_response"
          - "endpoint"
          - "http_method"
        description: >-
          This model captures performance and interoperability data for a PSU. Since only failure case data is included in the PSU network 'Report' model, it is important to have PSUs self report on nominal elements. This information may inform future performance requirements and forensics of certain incidents. This may be an initial model that will be required operationally in terms of a PSUs need to log interactions with other PSUs.
        properties:
          exchanged_data_pk:
            description: >-
              	The primary key of the data that were exchanged. For example, if an Operation or Constraint was exchanged, then this field would contain the reference ID.

                In the case that multiple data elements were exchanged, then just populate this field with one of the primary keys. As a best practice, choose the first one in the array as they were sent between PSUs.
            type: string
            format: uuid
            maxLength: 36
            minLength: 36
            pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[8-9a-bA-B][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
            example: "00000000-0000-4444-8888-FEEDDEADBEEF"
          exchanged_data_type:
            type: "string"
            enum:
              - OPERATION
              - TELEMETRY
              - CONSTRAINT
              - DISCOVERY
              - REPORT
              - OTHER_SEE_COMMENT
            example: "TELEMETRY"
          version_number:
            description: >-
              The version number of the model that was sent. For Operation and Constraint
            type: "integer"
            example: 4
          source_psu:
            description: >-
              This is the psu_name of the source_psu.
            type: "string"
          target_psu:
            description: >-
              This is the psu_name of the target_psu.
            type: "string"
          reporting_psu_role:
            description: >-
              An enum indicating if the PSU providing these data was the one that initiated the request (source_psu) or the PSU that received the request (target_psu).
            type: "string"
            enum:
              - SOURCE_PSU
              - TARGET_PSU
          time_request_initiation:
            description: >-
              If SOURCE_PSU, this is the time that the request is sent to the TARGET_USS.
              If TARGET_PSU, this is the time that the request was received from the SOURCE_PSU.
            $ref: '#/components/schemas/Timestamp'
          time_request_completed:
            description: >-
              If SOURCE_PSU, this is the time that the response was received from the TARGET_PSU.
              If TARGET_PSU, this is the time that the request was sent back to the SOURCE_PSU.
            $ref: '#/components/schemas/Timestamp'
          endpoint:
            description: >-
              The endpoint to which the data request was initially sent.
            type: "string"
            example: "https://utm.cool-uss-team.com/operations"
          http_method:
            description: >-
              The HTTP method used in this exchange.
            type: string
            enum:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - TRACE
              - OPTIONS
              - CONNECT
              - PATCH
            example: "PUT"
          expected_http_response:
            description: >-
              The expected HTTP response code.
              This is required ONLY if the reporting_psu_role is source_psu.
            type: "integer"
            minimum: 100
            maximum: 599
            example: 204
          actual_http_response:
            description: >-
              The actual HTTP response code sent by the target_psu to the source_psu.
              Must be reported by USSs in either role.
            type: "integer"
            minimum: 100
            maximum: 599
            example: 204
          comments:
            description: >-
              Any additional comments that could aid in analysis involving these data.
            type: "string"
            maxLength: 1000
            example: "This test was good."

    Waypoint:
        description: A single waypoint with associated data.
        required:
          - sequence_id
          - waypoint_type
          - waypoint_location
          - target_time
          - target_air_speed
          - target_ground_speed
          - target_vertical_speed
          - hover_duration
        properties:
          sequence_id:
            description: >-
              	Integer indicating order of this waypoint in the list of waypoints.
                must be sequential starting with 1.
            type: integer
            format: int32
            minimum: 1
            maximum: 9999
            example: 23
          waypoint_type:
            description: Fly over or fly by?
            type: string
            enum:
              - FLY_BY
              - FLY_OVER
          waypoint_phase:
            description: >-
              Phase of flight that the operation will be in at this waypoint. Climb or Descent implies that the vehicle is traveling with some lateral air speed while descending. Vertical implies no lateral speed.
            type: string
            enum:
              - HOVER
              - VERTICAL_CLIMB
              - CLIMB
              - CRUISE
              - VERTICAL_DESCENT
              - DESCENT
          waypoint_location:
            description: >-
              For Lat/Lon, report at least seven decimal degrees. (deg)
              For Alt, express in WGS84 standard. (ft)
            $ref: '#/components/schemas/LatLonAlt'
          target_time:
            description: Targeted time to reach this waypoint.
            $ref: '#/components/schemas/Timestamp'
          target_air_speed:
            description: >-
              The target air speed of the vehicle at this waypoint.
              Units of measure: ft/sec.
            type: integer
            format: int32
            minimum: -9999
            maximum: 9999
            example: 32
          target_ground_speed:
            description: >-
              The target ground speed of the vehicle at this waypoint.
              Units of measure: ft/sec.
            type: integer
            format: int32
            minimum: 0
            maximum: 9999
            example: 32
          target_vertical_speed:
            description: >-
              For climb and descent waypoints, the target speed of climb or descent
              Units of measure: ft/sec.
            type: integer
            format: int32
            minimum: -9999
            maximum: 9999
            example: 32
          hover_duration:
            description: >-
              Number of seconds the vehicle plans to hover or loiter at this waypoint.
            type: integer
            format: int32
            minimum: 0
            maximum: 99999
            example: 120

  responses:

    'r200':
      description: an existing position resource updated
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r201':
      description: Position data created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r204':
      description: no response supplied

    'r400':
      description: Bad request. Typically validation error. Fix your request and retry.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r401':
      description: Invalid or missing access_token provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r403':
      description: >-
        Forbidden. Do not retry with same access token. Reason not provided,
        but do you have the right scopes? Does uss_name match the sub claim?
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r409':
      description: Conflict for a PUT that is unsuccessful due to a 3rd-party modification
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'

    'r429':
      description: Too many recent requests from you. Wait to make further queries.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UTMRestResponse'
